[{"ContainerToolsException.Message":"Docker 命令失败，退出代码为 1。 #1 [internal] load .dockerignore #1 transferring context: 35B done #1 DONE 0.1s  #2 [internal] load build definition from Dockerfile #2 transferring dockerfile: 32B done #2 DONE 0.1s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste... #3 ...  #4 [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1-bu... #4 DONE 0.0s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste... #3 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:36871->192.168.65.1:53: i/o timeout  #10 [internal] load build context #10 DONE 0.0s  #5 [base 1/2] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim #5 DONE 0.0s  #8 [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster #8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster #8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster 10.0s done #8 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:49082->192.168.65.1:53: i/o timeout ------  > [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buster: ------ ------  > [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster: ------ failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:49082->192.168.65.1:53: i/o timeout","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   在 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__12.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__176.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"#1 [internal] load .dockerignore\r\n#1 transferring context: 35B done\r\n#1 DONE 0.1s\r\n\r\n#2 [internal] load build definition from Dockerfile\r\n#2 transferring dockerfile: 32B done\r\n#2 DONE 0.1s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste...\r\n#3 ...\r\n\r\n#4 [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1-bu...\r\n#4 DONE 0.0s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste...\r\n#3 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:36871->192.168.65.1:53: i/o timeout\r\n\r\n#10 [internal] load build context\r\n#10 DONE 0.0s\r\n\r\n#5 [base 1/2] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim\r\n#5 DONE 0.0s\r\n\r\n#8 [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster\r\n#8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster\r\n#8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster 10.0s done\r\n#8 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:49082->192.168.65.1:53: i/o timeout\r\n------\r\n > [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buster:\r\n------\r\n------\r\n > [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster:\r\n------\r\nfailed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:49082->192.168.65.1:53: i/o timeout"},{"ContainerToolsException.Message":"Docker 命令失败，退出代码为 1。 #1 [internal] load .dockerignore #1 transferring context: 35B done #1 DONE 0.1s  #2 [internal] load build definition from Dockerfile #2 transferring dockerfile: 32B done #2 DONE 0.1s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste... #3 ...  #4 [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1-bu... #4 DONE 0.0s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste... #3 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:42363->192.168.65.1:53: i/o timeout  #10 [internal] load build context #10 DONE 0.0s  #5 [base 1/2] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim #5 DONE 0.0s  #8 [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster #8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster #8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster 1.1s done #8 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: no such host ------  > [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buster: ------ ------  > [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster: ------ failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: no such host","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   在 Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__4.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__12.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__176.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"#1 [internal] load .dockerignore\r\n#1 transferring context: 35B done\r\n#1 DONE 0.1s\r\n\r\n#2 [internal] load build definition from Dockerfile\r\n#2 transferring dockerfile: 32B done\r\n#2 DONE 0.1s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste...\r\n#3 ...\r\n\r\n#4 [internal] load metadata for mcr.microsoft.com/dotnet/core/aspnet:3.1-bu...\r\n#4 DONE 0.0s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buste...\r\n#3 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:42363->192.168.65.1:53: i/o timeout\r\n\r\n#10 [internal] load build context\r\n#10 DONE 0.0s\r\n\r\n#5 [base 1/2] FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim\r\n#5 DONE 0.0s\r\n\r\n#8 [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster\r\n#8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster\r\n#8 resolve mcr.microsoft.com/dotnet/core/sdk:3.1-buster 1.1s done\r\n#8 ERROR: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: no such host\r\n------\r\n > [internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:3.1-buster:\r\n------\r\n------\r\n > [build 1/7] FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster:\r\n------\r\nfailed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://mcr.microsoft.com/v2/dotnet/core/sdk/manifests/3.1-buster: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: no such host"}]